nature_list = [("adamant", "attack", "special-attack"),
               ("bashful", "special-attack", "special-attack"),
               ("bold", "defense", "attack"),
               ("brave", "attack", "speed"),
               ("calm", "special-defense", "attack"),
               ("careful", "special-defense", "special-attack"),
               ("docile", "defense", "defense"),
               ("gentle", "special-defense", "defense"),
               ("hardy", "attack", "attack"),
               ("hasty", "speed", "defense"),
               ("impish", "defense", "special-attack"),
               ("jolly", "speed", "special-attack"),
               ("lax", "defense", "special-defense"),
               ("lonely", "attack", "defense"),
               ("mild", "special-attack", "defense"),
               ("modest", "special-attack", "attack"),
               ("naive", "speed", "special-defense"),
               ("naughty", "attack", "special-defense"),
               ("quiet", "special-attack", "speed"),
               ("quirky", "special-defense", "special-defense"),
               ("rash", "special-attack", "special-defense"),
               ("relaxed", "defense", "speed"),
               ("sassy", "special-defense", "speed"),
               ("serious", "speed", "speed"),
               ("timid", "speed", "attack")
               ]